# grab data
```{r load libraries}
library(tidyverse)
library(plotly)
library(lubridate)
library(sqldf)
```

#import data
```{r import csv}
df_nfl_2023 <- read_csv("Data/play_by_play_2023.csv")
```

#subset data
```{r select only 49ers}
df_49ers <- df_nfl_2023 %>%
  subset(home_team == 'SF' | away_team == 'SF')
```

#initial plots
```{r week delineation}
#plotting just by each individual YAC per completed pass attempt with no grouping per week
#realizing that the base plot did not parse if SF was on offense or not so rethinking the displayed data
YAC_by_week_plot <- df_49ers %>% 
  subset(season_type == 'REG') %>% #only looking at regular season in this plot
  subset(posteam == 'SF') %>% #only looking when SF was on the offensive side of the ball
  group_by(week) %>%
  plot_ly(x = ~week,
          y = ~yards_after_catch,
          color = ~posteam_type, #colored by team with possession, here filtered as SF, being home or away game
          #legendgroup = ~paste(month_year, gro_status), 
          text = ~paste("Drive :", drive,
                        "Quarter :", qtr,
                        "Receiver :", receiver_player_name),
          hoverinfo = "text",
          type = "scattergl",
          mode = "markers",
          symbol = ~receiver_player_name, #different shape points for different receivers to see if there's a trend
          #symbols = (c(16, 8)),
          #showlegend = FALSE,
          marker = list(size = 14,
                        opacity = 0.9),
          colors = c("blue", "red"))
```

```{r YAC by player}
YAC_by_player_plot <- df_49ers %>% 
  subset(!is.na(receiver_player_name)) %>%    # Remove rows where there was no pass (completion)
  subset(season_type == 'REG') %>% #only looking at regular season in this plot
  subset(posteam == 'SF') %>% #only looking at when SF had the ball on offense
  subset(posteam_type == 'home') %>% #only looking at home games
  #group_by(week) %>% #looking at productivity per week - more targeted or effective in certain weeks? 
  plot_ly(x = ~as.factor(receiver_player_name), 
          y = ~yards_after_catch, 
          type = 'scatter', 
          mode = 'markers',
          color = ~as.factor(qtr),   # colored by qtr
          symbol = ~week,    # Different symbols for each week
          #size = ~drive,        # Size of points based on the drive number
          marker = list(size = 14, opacity = 0.9), 
          hoverinfo = "text", 
          text = ~paste("Receiver:", receiver_player_name, "<br>Yards After Catch:", yards_after_catch,
                        "<br>Week:", week, "<br>Quarter:", qtr, "<br>Drive:", drive)) %>%
  layout(title = "Yards After Catch by Receiver with Week, Quarter, & Drive",
         xaxis = list(title = "Receiver"),
         yaxis = list(title = "Yards After Catch")) %>%
  layout(legend = list(title = list(text='<b> Quarter </b>'),
                       orientation = "h",   # show entries horizontally
                       xanchor = "center",  # use center of legend as anchor
                       yanchor = "bottom",  # use bottom as anchor                       
                       x = 0.5,             # put legend in center of x-axis
                       y = -0.2,                # and at bottom of y-axis
                       font = list (size = 15), #change the size of the font of the legend
                       marker = list(size = 5),
                       itemsizing = "constant", 
                       bgcolor = "rgba(0, 0, 0, 0)")) #makes the background of legend transparent
```